import { PrismaClient } from "../src/generated/prisma/client";
import { PrismaLibSql } from "@prisma/adapter-libsql";
import bcrypt from "bcryptjs";

const adapter = new PrismaLibSql({ url: process.env.DATABASE_URL ?? "file:./prisma/dev.db" });
const db = new PrismaClient({ adapter });

function slug(str: string): string {
  return str
    .toLowerCase()
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
}

async function main() {
  console.log("🌱 Seed Nuvora…");

  // ── Wipe ──────────────────────────────────────────────────────────────────
  await db.review.deleteMany();
  await db.product.deleteMany();
  await db.creator.deleteMany();
  await db.user.deleteMany();

  // ── Admin ─────────────────────────────────────────────────────────────────
  await db.user.create({
    data: {
      email: "admin@nuvora.app",
      password: await bcrypt.hash("admin1234", 12),
      name: "Admin Nuvora",
      role: "admin",
    },
  });

  // ── Créateurs ─────────────────────────────────────────────────────────────
  const creatorsData = [
    {
      name: "Studio Lumen",
      email: "lumen@nuvora.app",
      tagline: "IA appliquée & marketing de contenu",
      bio: "<p>Studio spécialisé dans la création de formations autour de l'IA et du copywriting. Nos produits sont pensés pour les créateurs et entrepreneurs qui veulent gagner du temps sans sacrifier la qualité.</p>",
      specialty: "IA & Marketing",
      platform: "Gumroad",
      verified: true,
    },
    {
      name: "Amélie R.",
      email: "amelie@nuvora.app",
      tagline: "Solopreneure · Business digital",
      bio: "<p>J'aide les solopreneurs à structurer et lancer leur première offre digitale. Après avoir accompagné plus de 200 créateurs, j'ai mis ma méthode en forme dans des guides pratiques.</p>",
      specialty: "Business & Offre",
      platform: "Gumroad",
      verified: true,
    },
    {
      name: "Koda",
      email: "koda@nuvora.app",
      tagline: "Templates Notion pour créateurs",
      bio: "<p>Je conçois des systèmes de productivité dans Notion pour les créateurs de contenu et freelances. Chaque template est testé en conditions réelles.</p>",
      specialty: "Notion & Productivité",
      platform: "Chariow",
      verified: true,
    },
    {
      name: "DevAcademy",
      email: "devacademy@nuvora.app",
      tagline: "Formations web en français, du débutant au pro",
      bio: "<p>DevAcademy propose des formations vidéo complètes pour apprendre le développement web en français. Plus de 40 h de contenu, des projets concrets et un accès à vie.</p>",
      specialty: "Dev web",
      platform: "Systeme.io",
      verified: true,
    },
    {
      name: "M. Diallo",
      email: "mdiallo@nuvora.app",
      tagline: "Growth & acquisition sans budget pub",
      bio: "<p>Consultant en acquisition depuis 8 ans, j'accompagne les créateurs solo qui veulent développer leur audience sans publicité. Mes formations distillent ce qui fonctionne vraiment.</p>",
      specialty: "Growth & Marketing",
      platform: "Gumroad",
      verified: true,
    },
    {
      name: "Atelier Pixel",
      email: "pixel@nuvora.app",
      tagline: "Design accessible & templates prêts à l'emploi",
      bio: "<p>Atelier Pixel crée des ressources design pour les non-designers : formations Figma pédagogiques et templates professionnels que n'importe qui peut personnaliser en une soirée.</p>",
      specialty: "Design & Templates",
      platform: "Chariow",
      verified: false,
    },
    {
      name: "C. Bernard",
      email: "cbernard@nuvora.app",
      tagline: "Finance personnelle sans jargon",
      bio: "<p>Ancien analyste financier reconverti formateur, j'explique l'investissement et la gestion de patrimoine avec des mots simples. Mon objectif : démocratiser la culture financière.</p>",
      specialty: "Finance & Investissement",
      platform: "Podia",
      verified: false,
    },
    {
      name: "SaaSFlow",
      email: "saasflow@nuvora.app",
      tagline: "Outils & automatisations pour indépendants",
      bio: "<p>SaaSFlow développe des micro-outils et des templates d'automatisation pour les freelances et TPE. Nos solutions sont légères, sans abonnement et faciles à déployer.</p>",
      specialty: "Automatisation & SaaS",
      platform: "Chariow",
      verified: true,
    },
  ];

  const HASH = await bcrypt.hash("creator1234", 12);
  const creatorMap: Record<string, string> = {}; // name → creatorId

  for (const c of creatorsData) {
    const s = slug(c.name);
    const user = await db.user.create({
      data: {
        email: c.email,
        password: HASH,
        name: c.name,
        role: "creator",
      },
    });
    const creator = await db.creator.create({
      data: {
        userId: user.id,
        slug: s,
        tagline: c.tagline,
        bio: c.bio,
        specialty: c.specialty,
        platform: c.platform,
        verified: c.verified,
      },
    });
    creatorMap[c.name] = creator.id;
  }

  // ── Produits ──────────────────────────────────────────────────────────────
  const products = [
    // ── Studio Lumen ──
    {
      creator: "Studio Lumen",
      title: "Maîtriser Claude & les agents IA",
      description: "Une formation complète pour concevoir et déployer des agents IA avec Claude. Vous apprendrez à rédiger des prompts avancés, chaîner des outils et automatiser vos workflows créatifs.",
      category: "Formation",
      subCategory: "IA",
      tags: ["ia", "claude", "agents", "prompts", "automatisation"],
      price: 79,
      isFree: false,
      language: "Français",
      country: "France",
      platform: "Gumroad",
      purchaseUrl: "https://gumroad.com/l/maitriser-claude",
      status: "active",
      views: 4820,
      clicks: 390,
    },
    {
      creator: "Studio Lumen",
      title: "Pack de prompts marketing IA",
      description: "200+ prompts prêts à l'emploi pour copywriting, réseaux sociaux, newsletters et SEO. Compatibles ChatGPT, Claude et Gemini. Résultats immédiats.",
      category: "Template",
      subCategory: "IA",
      tags: ["prompts", "copywriting", "marketing", "chatgpt", "ia"],
      price: 29,
      isFree: false,
      language: "Français",
      country: "France",
      platform: "Gumroad",
      purchaseUrl: "https://gumroad.com/l/pack-prompts-marketing",
      status: "active",
      views: 3210,
      clicks: 280,
    },
    {
      creator: "Studio Lumen",
      title: "Guide IA pour créateurs de contenu",
      description: "Ebook pratique de 80 pages pour intégrer l'IA dans votre workflow de création : articles, vidéos, newsletters, réseaux sociaux. Cas concrets et outils testés.",
      category: "Ebook",
      subCategory: "IA",
      tags: ["ia", "creation-contenu", "workflow", "outils-ia"],
      price: 19,
      isFree: false,
      language: "Français",
      country: "France",
      platform: "Gumroad",
      purchaseUrl: "https://gumroad.com/l/guide-ia-createurs",
      status: "active",
      views: 2100,
      clicks: 175,
    },

    // ── Amélie R. ──
    {
      creator: "Amélie R.",
      title: "Lancer son offre digitale en 30 jours",
      description: "La méthode complète pour créer, valider et lancer votre première offre digitale en 30 jours. Idéal pour les solopreneurs qui partent de zéro.",
      category: "Formation",
      subCategory: "Business",
      tags: ["business", "offre-digitale", "solopreneur", "lancement"],
      price: 97,
      isFree: false,
      language: "Français",
      country: "France",
      platform: "Gumroad",
      purchaseUrl: "https://gumroad.com/l/lancer-offre-30-jours",
      status: "active",
      views: 5640,
      clicks: 510,
    },
    {
      creator: "Amélie R.",
      title: "Ebook : Trouver sa niche rentable",
      description: "Comment identifier une niche où vous pouvez vous positionner avec autorité. Méthode de validation en 7 étapes, grille d'analyse et exemples réels.",
      category: "Ebook",
      subCategory: "Business",
      tags: ["niche", "business", "positionnement", "monetisation"],
      price: 24,
      isFree: false,
      language: "Français",
      country: "France",
      platform: "Gumroad",
      purchaseUrl: "https://gumroad.com/l/trouver-niche-rentable",
      status: "active",
      views: 2980,
      clicks: 230,
    },
    {
      creator: "Amélie R.",
      title: "Template tunnel de vente Notion",
      description: "Système complet pour gérer votre tunnel de vente dans Notion : pipeline prospects, suivi relances, tableaux de bord revenus. Prêt en 30 minutes.",
      category: "Template",
      subCategory: "Notion",
      tags: ["notion", "tunnel-vente", "crm", "solopreneur"],
      price: 0,
      isFree: true,
      language: "Français",
      country: "France",
      platform: "Gumroad",
      purchaseUrl: "https://gumroad.com/l/tunnel-vente-notion",
      status: "active",
      views: 6100,
      clicks: 820,
    },

    // ── Koda ──
    {
      creator: "Koda",
      title: "OS Créateur Notion — Système complet",
      description: "Le système Notion tout-en-un pour créateurs : gestion de projets, calendrier éditorial, base de connaissances, suivi revenus et CRM clients. Testé par 500+ créateurs.",
      category: "Template",
      subCategory: "Notion",
      tags: ["notion", "productivite", "createur", "organisation", "systeme"],
      price: 39,
      isFree: false,
      language: "Français",
      country: "Belgique",
      platform: "Chariow",
      purchaseUrl: "https://chariow.com/koda/os-createur-notion",
      status: "active",
      views: 7230,
      clicks: 640,
    },
    {
      creator: "Koda",
      title: "Template Notion Freelance Pro",
      description: "Gérez vos missions, clients, devis et factures depuis un seul workspace Notion. Calcul auto du TJM, suivi du temps, tableau de bord financier mensuel.",
      category: "Template",
      subCategory: "Notion",
      tags: ["notion", "freelance", "gestion", "factures", "tjm"],
      price: 27,
      isFree: false,
      language: "Français",
      country: "Belgique",
      platform: "Chariow",
      purchaseUrl: "https://chariow.com/koda/freelance-pro",
      status: "active",
      views: 3450,
      clicks: 290,
    },
    {
      creator: "Koda",
      title: "Second Brain Notion — Starter",
      description: "Votre cerveau numérique dans Notion : capture d'idées, notes liées, zones projets et archives. Basé sur la méthode PARA. Prise en main en 20 min.",
      category: "Template",
      subCategory: "Notion",
      tags: ["notion", "second-brain", "pkm", "notes", "organisation"],
      price: 0,
      isFree: true,
      language: "Français",
      country: "Belgique",
      platform: "Chariow",
      purchaseUrl: "https://chariow.com/koda/second-brain-starter",
      status: "active",
      views: 9120,
      clicks: 1200,
    },

    // ── DevAcademy ──
    {
      creator: "DevAcademy",
      title: "Formation React & Next.js — Du débutant au pro",
      description: "40 heures de vidéo pour maîtriser React 19 et Next.js 15. Projets réels, App Router, Server Components, authentification et déploiement. Accès à vie.",
      category: "Formation",
      subCategory: "Dev",
      tags: ["react", "nextjs", "javascript", "frontend", "web"],
      price: 129,
      isFree: false,
      language: "Français",
      country: "France",
      platform: "Systeme.io",
      purchaseUrl: "https://systeme.io/devacademy/react-nextjs",
      status: "active",
      views: 8900,
      clicks: 720,
    },
    {
      creator: "DevAcademy",
      title: "Formation TypeScript Complet",
      description: "Passez de JavaScript à TypeScript en 15 heures de formation. Types, interfaces, génériques, utilitaires avancés. Exercices pratiques et projets guidés.",
      category: "Formation",
      subCategory: "Dev",
      tags: ["typescript", "javascript", "dev", "programmation"],
      price: 69,
      isFree: false,
      language: "Français",
      country: "France",
      platform: "Systeme.io",
      purchaseUrl: "https://systeme.io/devacademy/typescript",
      status: "active",
      views: 4120,
      clicks: 340,
    },
    {
      creator: "DevAcademy",
      title: "Formation Python pour l'IA",
      description: "Maîtrisez Python appliqué à l'IA : NumPy, Pandas, scikit-learn, et introduction aux LLMs. 20h de formation avec projets de machine learning concrets.",
      category: "Formation",
      subCategory: "IA",
      tags: ["python", "ia", "machine-learning", "data-science"],
      price: 89,
      isFree: false,
      language: "Français",
      country: "France",
      platform: "Systeme.io",
      purchaseUrl: "https://systeme.io/devacademy/python-ia",
      status: "active",
      views: 5670,
      clicks: 490,
    },
    {
      creator: "DevAcademy",
      title: "Cheatsheet Git & GitHub",
      description: "Toutes les commandes Git essentielles en un PDF : branches, merge, rebase, stash, hooks, CI/CD GitHub Actions. Format A4 prêt à imprimer.",
      category: "Template",
      subCategory: "Autre",
      tags: ["git", "github", "dev", "cheatsheet"],
      price: 0,
      isFree: true,
      language: "Français",
      country: "France",
      platform: "Systeme.io",
      purchaseUrl: "https://systeme.io/devacademy/cheatsheet-git",
      status: "active",
      views: 11200,
      clicks: 1850,
    },

    // ── M. Diallo ──
    {
      creator: "M. Diallo",
      title: "Formation Growth Organique 0 à 10k abonnés",
      description: "Stratégie complète pour passer de 0 à 10 000 abonnés sans publicité payante. Méthode éprouvée sur LinkedIn, Instagram et newsletter. 12h de contenu.",
      category: "Formation",
      subCategory: "Marketing",
      tags: ["growth", "audience", "linkedin", "instagram", "newsletter"],
      price: 87,
      isFree: false,
      language: "Français",
      country: "Sénégal",
      platform: "Gumroad",
      purchaseUrl: "https://gumroad.com/l/growth-0-10k",
      status: "active",
      views: 4350,
      clicks: 380,
    },
    {
      creator: "M. Diallo",
      title: "Ebook : L'acquisition sans pub en 2025",
      description: "Les stratégies d'acquisition organique qui fonctionnent en 2025 : SEO, bouche-à-oreille, partenariats et contenu viral. 120 pages, exemples chiffrés.",
      category: "Ebook",
      subCategory: "Marketing",
      tags: ["acquisition", "seo", "contenu", "marketing", "growth"],
      price: 34,
      isFree: false,
      language: "Français",
      country: "Sénégal",
      platform: "Gumroad",
      purchaseUrl: "https://gumroad.com/l/acquisition-sans-pub",
      status: "active",
      views: 2760,
      clicks: 215,
    },

    // ── Atelier Pixel ──
    {
      creator: "Atelier Pixel",
      title: "Formation Figma — Design UI de A à Z",
      description: "Apprenez Figma en partant de zéro : composants, auto-layout, variables de design, prototypage et handoff développeur. 18h de vidéo, projets réels.",
      category: "Formation",
      subCategory: "Design",
      tags: ["figma", "design", "ui", "ux", "interface"],
      price: 74,
      isFree: false,
      language: "Français",
      country: "Canada",
      platform: "Chariow",
      purchaseUrl: "https://chariow.com/atelier-pixel/figma-design",
      status: "active",
      views: 3890,
      clicks: 330,
    },
    {
      creator: "Atelier Pixel",
      title: "Kit UI Figma — Composants minimalistes",
      description: "200+ composants Figma en style minimaliste : boutons, formulaires, cartes, navigations, modales. Variables de couleur, dark mode inclus. Licence commerciale.",
      category: "Template",
      subCategory: "Figma",
      tags: ["figma", "ui-kit", "composants", "design", "minimaliste"],
      price: 49,
      isFree: false,
      language: "Français",
      country: "Canada",
      platform: "Chariow",
      purchaseUrl: "https://chariow.com/atelier-pixel/kit-ui-figma",
      status: "active",
      views: 5120,
      clicks: 470,
    },
    {
      creator: "Atelier Pixel",
      title: "Template Framer — Landing page SaaS",
      description: "Template Framer pour SaaS moderne : hero, features, pricing, FAQ, testimonials, CTA. 100% personnalisable, responsive, animations incluses.",
      category: "Template",
      subCategory: "Framer",
      tags: ["framer", "landing-page", "saas", "website", "template"],
      price: 59,
      isFree: false,
      language: "Anglais",
      country: "Canada",
      platform: "Chariow",
      purchaseUrl: "https://chariow.com/atelier-pixel/framer-saas",
      status: "active",
      views: 4230,
      clicks: 390,
    },

    // ── C. Bernard ──
    {
      creator: "C. Bernard",
      title: "Ebook : Investir en bourse pour débutants",
      description: "Guide complet pour commencer à investir en bourse sans jargon financier. ETF, DCA, gestion des risques, psychologie de l'investisseur. 150 pages illustrées.",
      category: "Ebook",
      subCategory: "Finance",
      tags: ["bourse", "investissement", "etf", "finance-personnelle", "debutant"],
      price: 29,
      isFree: false,
      language: "Français",
      country: "France",
      platform: "Podia",
      purchaseUrl: "https://podia.com/cbernard/investir-bourse",
      status: "active",
      views: 6780,
      clicks: 590,
    },
    {
      creator: "C. Bernard",
      title: "Formation : Construire son portefeuille ETF",
      description: "6 heures de formation pour construire un portefeuille ETF adapté à votre profil. Sélection des ETF, allocation, rééquilibrage et fiscalité française.",
      category: "Formation",
      subCategory: "Finance",
      tags: ["etf", "bourse", "portefeuille", "investissement", "finance"],
      price: 67,
      isFree: false,
      language: "Français",
      country: "France",
      platform: "Podia",
      purchaseUrl: "https://podia.com/cbernard/portefeuille-etf",
      status: "active",
      views: 3210,
      clicks: 265,
    },
    {
      creator: "C. Bernard",
      title: "Calculateur budget & épargne — Excel",
      description: "Tableau Excel prêt à l'emploi pour gérer son budget mensuel, suivre son épargne et simuler sa retraite. Formules automatisées, graphiques inclus.",
      category: "Template",
      subCategory: "Excel",
      tags: ["excel", "budget", "epargne", "finance-personnelle", "retraite"],
      price: 14,
      isFree: false,
      language: "Français",
      country: "France",
      platform: "Podia",
      purchaseUrl: "https://podia.com/cbernard/calculateur-budget",
      status: "active",
      views: 4560,
      clicks: 520,
    },

    // ── SaaSFlow ──
    {
      creator: "SaaSFlow",
      title: "Automatisations Make.com pour freelances",
      description: "20 scénarios Make.com prêts à importer : synchronisation clients, facturation automatique, relances, rapports hebdomadaires. Sans code, sans abonnement élevé.",
      category: "Logiciel",
      subCategory: "Plugin",
      tags: ["make", "automatisation", "no-code", "freelance", "workflow"],
      price: 47,
      isFree: false,
      language: "Français",
      country: "France",
      platform: "Chariow",
      purchaseUrl: "https://chariow.com/saasflow/automatisations-make",
      status: "active",
      views: 2890,
      clicks: 240,
    },
    {
      creator: "SaaSFlow",
      title: "SaaS Starter Kit — Next.js + Stripe",
      description: "Boilerplate Next.js 15 complet pour lancer un SaaS : authentification, paiement Stripe, dashboard, emails transactionnels, déploiement Vercel. Prêt en 2h.",
      category: "Logiciel",
      subCategory: "SaaS",
      tags: ["nextjs", "saas", "stripe", "boilerplate", "starter-kit"],
      price: 149,
      isFree: false,
      language: "Anglais",
      country: "France",
      platform: "Chariow",
      purchaseUrl: "https://chariow.com/saasflow/saas-starter-kit",
      status: "active",
      views: 5430,
      clicks: 480,
    },
    {
      creator: "SaaSFlow",
      title: "Extension Chrome — Suivi de temps freelance",
      description: "Extension Chrome légère pour tracker son temps par projet et client directement depuis le navigateur. Export CSV, résumé hebdomadaire, 100% offline.",
      category: "Logiciel",
      subCategory: "Extension",
      tags: ["chrome", "extension", "temps", "freelance", "productivite"],
      price: 19,
      isFree: false,
      language: "Français",
      country: "France",
      platform: "Chariow",
      purchaseUrl: "https://chariow.com/saasflow/extension-suivi-temps",
      status: "active",
      views: 3670,
      clicks: 310,
    },
    {
      creator: "SaaSFlow",
      title: "Formation : Créer son SaaS sans être dev",
      description: "De l'idée au premier client payant sans coder : Bubble, Glide, Airtable, Stripe. 10h de formation avec 3 projets complets construits pas à pas.",
      category: "Formation",
      subCategory: "Logiciel",
      tags: ["saas", "no-code", "bubble", "airtable", "entrepreneuriat"],
      price: 99,
      isFree: false,
      language: "Français",
      country: "France",
      platform: "Chariow",
      purchaseUrl: "https://chariow.com/saasflow/creer-saas-sans-dev",
      status: "active",
      views: 4780,
      clicks: 420,
    },
  ];

  for (const p of products) {
    const creatorId = creatorMap[p.creator];
    if (!creatorId) { console.warn(`Créateur introuvable : ${p.creator}`); continue; }

    await db.product.create({
      data: {
        slug: slug(p.title),
        title: p.title,
        description: p.description,
        category: p.category,
        subCategory: p.subCategory,
        tags: JSON.stringify(p.tags),
        price: p.price,
        isFree: p.isFree,
        language: p.language,
        country: p.country,
        platform: p.platform,
        purchaseUrl: p.purchaseUrl,
        status: p.status,
        views: p.views,
        clicks: p.clicks,
        creatorId,
      },
    });
  }

  const counts = { users: await db.user.count(), creators: await db.creator.count(), products: await db.product.count() };
  console.log(`✅ Seed terminé — ${counts.users} users, ${counts.creators} créateurs, ${counts.products} produits`);
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => db.$disconnect());
